export const permissions = Object.freeze({
  COMPANY_VIEW: "COMPANY_VIEW",
  COMPANY_UPDATE: "COMPANY_UPDATE",
  COMPANY_MANAGE_SETTINGS: "COMPANY_MANAGE_SETTINGS",
  USER_VIEW: "USER_VIEW",
  USER_VIEW_ALL: "USER_VIEW_ALL",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DEACTIVATE: "USER_DEACTIVATE",
  USER_ACTIVATE: "USER_ACTIVATE",
  USER_DELETE: "USER_DELETE",
  USER_ASSIGN_ROLE: "USER_ASSIGN_ROLE",
  USER_ASSIGN_JOB_TITLE: "USER_ASSIGN_JOB_TITLE",
  DEPARTMENT_VIEW: "DEPARTMENT_VIEW",
  JOB_TITLE_VIEW: "JOB_TITLE_VIEW",
  ROLE_VIEW: "ROLE_VIEW",
  ROOM_VIEW: "ROOM_VIEW",
  ROOM_VIEW_AVAILABILITY: "ROOM_VIEW_AVAILABILITY",
  ROOM_UPDATE: "ROOM_UPDATE",
  FEATURE_VIEW: "FEATURE_VIEW",
  RESERVATION_CREATE: "RESERVATION_CREATE",
  RESERVATION_VIEW_OWN: "RESERVATION_VIEW_OWN",
  RESERVATION_VIEW_ALL: "RESERVATION_VIEW_ALL",
  RESERVATION_VIEW_DETAILS: "RESERVATION_VIEW_DETAILS",
  RESERVATION_APPROVE: "RESERVATION_APPROVE",
  RESERVATION_REJECT: "RESERVATION_REJECT",
  RESERVATION_CANCEL_ALL: "RESERVATION_CANCEL_ALL",
  RESERVATION_UPDATE_OWN: "RESERVATION_UPDATE_OWN",
  RESERVATION_CANCEL_OWN: "RESERVATION_CANCEL_OWN",
  RESERVATION_FILTER_BY_DATE: "RESERVATION_FILTER_BY_DATE",
  RESERVATION_FILTER_BY_ROOM: "RESERVATION_FILTER_BY_ROOM",
  VISITOR_CREATE: "VISITOR_CREATE",
  VISITOR_VIEW: "VISITOR_VIEW",
  VISITOR_CANCEL: "VISITOR_CANCEL",
  DASHBOARD_VIEW: "DASHBOARD_VIEW",
  NOTIFICATION_VIEW: "NOTIFICATION_VIEW",
  NOTIFICATION_MANAGE_SETTINGS: "NOTIFICATION_MANAGE_SETTINGS",
  REPORT_VIEW_ROOM_USAGE: "REPORT_VIEW_ROOM_USAGE",
  REPORT_VIEW_RESERVATION_STATS: "REPORT_VIEW_RESERVATION_STATS",
  REPORT_VIEW_CANCELLATION_STATS: "REPORT_VIEW_CANCELLATION_STATS",
  REPORT_EXPORT_EXCEL: "REPORT_EXPORT_EXCEL",
  AUDIT_LOG_VIEW: "AUDIT_LOG_VIEW",
});

export function hasPermission(userPermissions, permission) {
  return userPermissions.includes(permission);
}

const managementAccessPermissions = [
  permissions.USER_VIEW_ALL,
  permissions.ROLE_VIEW,
  permissions.ROOM_UPDATE,
  permissions.RESERVATION_VIEW_ALL,
  permissions.COMPANY_UPDATE,
  permissions.COMPANY_MANAGE_SETTINGS,
  permissions.REPORT_VIEW_ROOM_USAGE,
];

export function canAccessManagement(session) {
  return Boolean(session?.user?.owner)
    || managementAccessPermissions.some((permission) => hasPermission(session?.permissions ?? [], permission));
}
