export const permissions = Object.freeze({
  COMPANY_VIEW: "COMPANY_VIEW",
  USER_VIEW: "USER_VIEW",
  ROOM_VIEW: "ROOM_VIEW",
  ROOM_VIEW_AVAILABILITY: "ROOM_VIEW_AVAILABILITY",
  FEATURE_VIEW: "FEATURE_VIEW",
  RESERVATION_CREATE: "RESERVATION_CREATE",
  RESERVATION_VIEW_OWN: "RESERVATION_VIEW_OWN",
  RESERVATION_UPDATE_OWN: "RESERVATION_UPDATE_OWN",
  RESERVATION_CANCEL_OWN: "RESERVATION_CANCEL_OWN",
  RESERVATION_FILTER_BY_DATE: "RESERVATION_FILTER_BY_DATE",
  RESERVATION_FILTER_BY_ROOM: "RESERVATION_FILTER_BY_ROOM",
  VISITOR_CREATE: "VISITOR_CREATE",
  VISITOR_VIEW: "VISITOR_VIEW",
  VISITOR_CANCEL: "VISITOR_CANCEL",
  DASHBOARD_VIEW: "DASHBOARD_VIEW",
  NOTIFICATION_VIEW: "NOTIFICATION_VIEW",
});

export function hasPermission(userPermissions, permission) {
  return userPermissions.includes(permission);
}

